added jpa database
blazejbujala/invoicing-system-blazej-bujala pull request #14
Opened 2022-03-03 21:57 UTC by blazejbujala

2022-03-07 08:18 UTC, radoslawdabrowski requested changes

2022-03-07 08:18 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/db/Database.java
> +public interface Database extends PagingAndSortingRepository<Invoice, UUID> {
This class should have be named InvoiceRepository - this is a standard naming convention for jpa repos.

2022-03-08 19:33 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/db/Database.java
> +public interface Database extends PagingAndSortingRepository<Invoice, UUID> {
changed to JpaInvoiceRepository

2022-03-09 18:30 UTC, radoslawdabrowski approved these changes

2022-03-09 19:25 UTC, stanleyszysz approved these changes

2022-03-10 17:50 UTC, merged