Added Jaccoco and Gtihub Action
blazejbujala/invoicing-system-blazej-bujala pull request #2
Opened 2021-12-30 13:24 UTC by blazejbujala

2022-01-03 07:42 UTC, radoslawdabrowski requested changes

2022-01-03 07:42 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/model/InvoiceEntry.java
> +    public InvoiceEntry(String description, BigDecimal price, Vat vatRate) {
You can replace it with @AllArgsConstructor

2022-01-03 07:42 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/services/InvoiceService.java
> +    public List<Invoice> filterByIssuersTaxIdentificationNumber(String taxIdentificationNumber) {
This service should only have methods: `add`, `getById`, `getAll`, `update` and `delete`

2022-01-03 07:42 UTC, radoslawdabrowski commented on app/src/test/groovy/pl/futurecollars/invoicing/model/CompanyTest.groovy
> +    def "should add new object to the class"() {
Misleading test name. There is no such a thing as adding object to the class. I suggest `should be able to create instance of the class`

2022-01-03 09:03 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/services/InvoiceService.java
> +    public List<Invoice> filterByIssuersTaxIdentificationNumber(String taxIdentificationNumber) {
Understand from the task that there should be other methods too - like fillter etc.
 "c)    InvoiceService - class representing the logic - it will save invoices to database, search for it, filter etc."

2022-01-03 09:32 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/services/InvoiceService.java
> +    public List<Invoice> filterByIssuersTaxIdentificationNumber(String taxIdentificationNumber) {
Yes, this is correct, but filtering should be implement in the methods getById and getAll, not as separate methods. E.g. predicates. You can leave it without it for now, by searching we mean methods like get... or getAll and by filtering methods like e.g. ...byId. More advanced filtering will be implemented in next tasks.

2022-01-03 14:07 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/db/InMemoryRepository.java
> +            add(invoice);
noted

2022-01-03 14:07 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/db/InMemoryRepository.java
> +        return null;
noted, corrected

2022-01-03 14:07 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/db/InMemoryRepository.java
> +            return invoices.get(id);
changed

2022-01-03 14:09 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/model/Invoice.java
> +    public Invoice(UUID id, LocalDate dateOfIssue, Company issuer, Company receiver,
changed

2022-01-03 14:10 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/model/InvoiceEntry.java
> +    public InvoiceEntry(String description, BigDecimal price, Vat vatRate) {
cannot use @AllArgsConstructor - parametr vatValue is not beeing passed via constructor it is being calculated in this class.

2022-01-03 14:11 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/services/InvoiceService.java
> +    public List<Invoice> filterByIssuersTaxIdentificationNumber(String taxIdentificationNumber) {
noted, have delated methods and tests.

2022-01-03 14:11 UTC, blazejbujala commented on app/src/test/groovy/pl/futurecollars/invoicing/model/CompanyTest.groovy
> +    def "should add new object to the class"() {
changed

2022-01-03 14:48 UTC, radoslawdabrowski requested changes

2022-01-03 14:48 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/db/InMemoryRepository.java
> +            add(invoice);
Well, not correct. You need to return value that is returned from method invocation. So it will be:

`return add(invoice)`

or to be more clear:

You are creating invoice object and method add(_) returning this created object (line 17)
So you need to return reference to this object. eg. 

```
Invoice createdInvoiceInTheNextTry = add(invoice)
return createdInvoiceInTheNextTry;
```

2022-01-03 14:48 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/model/InvoiceEntry.java
> +    public InvoiceEntry(String description, BigDecimal price, Vat vatRate) {
oh, right

2022-01-04 09:49 UTC, radoslawdabrowski approved these changes

2022-01-04 12:59 UTC, bu0ne approved these changes

2022-01-04 13:11 UTC, merged