Added clasess with FileBasedREpository and tests
blazejbujala/invoicing-system-blazej-bujala pull request #3
Opened 2022-01-07 22:46 UTC by blazejbujala

2022-01-16 16:24 UTC, mtszpater commented on app/src/main/java/pl/futurecollars/invoicing/App.java
>  }
Jeżeli na ten moment nie potrzebujemy tej klasy to najlepiej byłoby ja po prostu usunąć. 

Nie rozumiem po co tutaj się pojawiło 'throws IOException' ;)

2022-01-16 16:24 UTC, mtszpater commented on app/src/main/java/pl/futurecollars/invoicing/db/file/FileBasedInvoiceRepository.java
> +        if (!checkId(id)) {
Ta nazwa metody 'checkId' jest troche malo opisowa. Skoro sprawdza ona czy ID jest zajęte to może lepiej byłoby to ciut inaczej zapisać np. 'if(jestWolne(id))`

czy cos takiego (celowo metoda po polsku, aby nie dać gotowca)

2022-01-16 16:24 UTC, mtszpater commented on app/src/main/java/pl/futurecollars/invoicing/db/file/FileBasedInvoiceRepository.java
> +        if (checkId(id)) {
Po co ten checkId tutaj? Skoro zawsze zwracamy 1 invoice to czy nie lepiej zrobić tak:

```
return getAll()
            .stream()
            .filter(invoice -> invoice.getId().equals(id))
            .findFirst();

```

2022-01-16 16:24 UTC, mtszpater commented on app/src/main/java/pl/futurecollars/invoicing/db/file/FileBasedInvoiceRepository.java
> +        if (checkId(id)) {
i od razu jak ladnie sie metoda uproscila

2022-01-16 16:24 UTC, mtszpater commented on app/src/main/java/pl/futurecollars/invoicing/db/file/FileBasedInvoiceRepository.java
> +        return add(updatedInvoice);
Czy aby na pewno ta metoda działa? Tzn. czy w pliku na pewno aktualizuje się ta faktura? Wygląda trochę jakby nie było takiej możliwości, bo w którym momencie z pliku kasujemy poprzednią fakturę?

` getAll().removeIf(item -> item.getId().equals(id));` to jedynie usuwa z listy, którą masz w pamięci, ale nie kasuje w ogóle z pliku

2022-01-16 16:24 UTC, mtszpater commented on app/src/test/groovy/pl/futurecollars/invoicing/AppTest.groovy
> +//        app.main()
A to co? ;)

2022-01-16 16:24 UTC, mtszpater commented on app/src/test/groovy/pl/futurecollars/invoicing/db/RepositoryTests.groovy
> +        def result = repository.delete(invoice.getId())
skoro nie używasz tego result w ogóle to wystarczy:
```
 when:
   repository.delete(invoice.getId())
```

2022-01-16 16:24 UTC, mtszpater commented on app/src/main/java/pl/futurecollars/invoicing/db/file/FileBasedInvoiceRepository.java
> +        return add(updatedInvoice);
z resztą pamiętaj, że updatedInvoice musi mieć to smao ID co poprzednie invoice. ID powinno zostać podczas aktualizacji niezmienne. W twojej metodzie jeżeli ktoś w updatedInvoice poda inne ID to nawet tego nie wyłapiesz.

2022-01-16 16:24 UTC, mtszpater commented on app/src/main/java/pl/futurecollars/invoicing/config/FileConfiguration.java
> +    public static final URL ID_DB_URL = FileService.class.getResource("/invoices.json");
chyba się ids.json z invoices.json pomyliły ;)

2022-01-16 16:24 UTC, mtszpater commented on app/src/main/java/pl/futurecollars/invoicing/config/FileConfiguration.java
> +    public static final URL ID_DB_URL = FileService.class.getResource("/invoices.json");
![image](https://user-images.githubusercontent.com/17989854/149668543-2e5c92fa-684a-4284-afe0-b7a0b221521a.png)

2022-01-16 17:21 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/App.java
>  }
deleted

2022-01-16 17:21 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/config/FileConfiguration.java
> +    public static final URL ID_DB_URL = FileService.class.getResource("/invoices.json");
changed

2022-01-16 17:21 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/db/file/FileBasedInvoiceRepository.java
> +        if (!checkId(id)) {
changed

2022-01-16 17:21 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/db/file/FileBasedInvoiceRepository.java
> +        if (checkId(id)) {
true :) method changed

2022-01-16 17:22 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/db/file/FileBasedInvoiceRepository.java
> +        return add(updatedInvoice);
corrected.

2022-01-16 17:22 UTC, blazejbujala commented on app/src/test/groovy/pl/futurecollars/invoicing/AppTest.groovy
> +//        app.main()
deleted whole AppTest

2022-01-16 17:22 UTC, blazejbujala commented on app/src/test/groovy/pl/futurecollars/invoicing/db/RepositoryTests.groovy
> +        def result = repository.delete(invoice.getId())
changed

2022-01-18 08:30 UTC, radoslawdabrowski requested changes

2022-01-18 08:30 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/config/FileConfiguration.java
> +        assert INVOICES_DB_URL != null;
not necessary

2022-01-18 08:30 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/services/FileService.java
> +            System.out.println("test");
change it to logger usage

2022-01-18 08:30 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/services/FileService.java
> +            System.out.println("test");
Or handle exception other way

2022-01-18 08:30 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/services/FileService.java
> +        return null;
maybe throw some exception?

2022-01-18 09:17 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/services/FileService.java
> +        return null;
changed

2022-01-18 09:17 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/services/FileService.java
> +            System.out.println("test");
changed

2022-01-18 09:17 UTC, blazejbujala commented on app/src/main/java/pl/futurecollars/invoicing/config/FileConfiguration.java
> +        assert INVOICES_DB_URL != null;
corrected

2022-01-18 09:41 UTC, radoslawdabrowski approved these changes

2022-01-18 16:11 UTC, stanleyszysz approved these changes

2022-01-18 17:25 UTC, merged